Description: CloudShirt ELK Stack

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: vockey

Resources:
  securityGroupElk1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: cloudshirt-elk-sg 
      GroupDescription: Security group for CloudShirt ELK instance
      VpcId: !ImportValue vpc1
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5601
          ToPort: 5601
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9200
          ToPort: 9200
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5044
          ToPort: 5044
          CidrIp: 0.0.0.0/0 
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: securityGroupElk1 

  elkInstance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.large  
      KeyName: !Ref KeyName 
      ImageId: ami-0bdd88bd06d16ba03 
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !ImportValue publicSubnet1
          GroupSet:
            - !Ref securityGroupElk1
      Tags:
        - Key: Name
          Value: elkInstance1 
      UserData: !Base64 |
        #!/bin/bash
        set -eux
        exec > /var/log/userdata.log 2>&1

        # --- Install dependencies ---
        yum install -y java-11

        # --- Add Elastic repo ---
        rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

        cat <<EOF > /etc/yum.repos.d/elasticsearch.repo
        [elasticsearch]
        name=Elasticsearch repository
        baseurl=https://artifacts.elastic.co/packages/8.x/yum
        gpgcheck=1
        gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled=1
        autorefresh=1
        type=rpm-md
        EOF

        yum clean all
        yum makecache

        # --- Install Elasticsearch, Logstash, Kibana ---
        yum install -y elasticsearch logstash kibana

        # --- Configure Elasticsearch ---
        cat <<EOF > /etc/elasticsearch/elasticsearch.yml
        network.host: 0.0.0.0
        http.port: 9200
        discovery.type: single-node
        xpack.security.enabled: false
        xpack.security.http.ssl.enabled: false
        xpack.security.transport.ssl.enabled: false
        EOF

        # Fix permissions
        mkdir -p /usr/share/elasticsearch/logs
        chown -R elasticsearch:elasticsearch /usr/share/elasticsearch
        chmod -R 755 /usr/share/elasticsearch

        systemctl enable elasticsearch
        systemctl start elasticsearch

        # --- Wait for Elasticsearch to respond ---
        for i in {1..30}; do
          if curl -s http://127.0.0.1:9200 >/dev/null; then
            echo "Elasticsearch is up!"
            break
          fi
          echo "Waiting for Elasticsearch..."
          sleep 5
        done

        # --- Configure Kibana ---
        cat <<EOF > /etc/kibana/kibana.yml
        server.host: "0.0.0.0"
        elasticsearch.hosts: ["http://localhost:9200"]
        EOF

        systemctl enable kibana
        systemctl start kibana

        # --- Configure Logstash ---
        mkdir -p /etc/logstash/conf.d
        cat <<'EOF' > /etc/logstash/conf.d/02-beats-input.conf
        input {
          beats {
            port => 5044
          }
        }
        filter {
          # pass-through
        }
        output {
          elasticsearch {
            hosts => ["http://localhost:9200"]
            index => "cloudshirt-%{+YYYY.MM.dd}"
          }
        }
        EOF

        systemctl enable logstash
        systemctl start logstash


Outputs:
  ELKPublicIP:
    Description: Public IP to access ELK instance
    Value: !GetAtt elkInstance1.PublicIp
    Export:
      Name: ELKPublicIP

  KibanaURL:
    Description: Kibana URL
    Value: !Sub "http://${elkInstance1.PublicIp}:5601"
