Description: CloudShirt ELK Stack (Development)

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: vockey

Resources:
  securityGroupElk1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: cloudshirt-elk-sg 
      GroupDescription: Security group for CloudShirt ELK instance
      VpcId: !ImportValue vpc1
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5601
          ToPort: 5601
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9200
          ToPort: 9200
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5044
          ToPort: 5044
          CidrIp: 0.0.0.0/0 
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: securityGroupElk1 

  elkInstance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.medium  
      KeyName: !Ref KeyName 
      ImageId: ami-0bdd88bd06d16ba03 
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !ImportValue publicSubnet1
          GroupSet:
            - !Ref securityGroupElk1
      Tags:
        - Key: Name
          Value: elkInstance1 
      UserData: !Base64 |
        #!/bin/bash
        set -e
        exec > /var/log/userdata.log 2>&1

        yum install java-11 -y

        # Add Elastic repo
        rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

        cat <<EOF > /etc/yum.repos.d/elasticsearch.repo
        [elasticsearch]
        name=Elasticsearch repository
        baseurl=https://artifacts.elastic.co/packages/8.x/yum
        gpgcheck=1
        gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled=0
        autorefresh=1
        type=rpm-md
        EOF

        # Import GPG key
        sudo rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

        # Update and refresh repo
        yum clean all
        yum makecache

        # Install stack
        yum install -y elasticsearch kibana logstash 

        # Basic single-node dev setup
        echo 'server.host: "0.0.0.0"' >> /etc/kibana/kibana.yml

        systemctl enable elasticsearch
        systemctl start elasticsearch

        # Wait for Elasticsearch to be up
        until curl -s http://localhost:9200 >/dev/null; do sleep 5; done

        systemctl enable kibana
        systemctl start kibana

        systemctl enable logstash
        systemctl start logstash
Outputs:
  ELKPublicIP:
    Description: Public IP to access ELK instance
    Value: !GetAtt elkInstance1.PublicIp

  KibanaURL:
    Description: Kibana URL
    Value: !Sub "http://${elkInstance1.PublicIp}:5601"
