Description: Application load balancer for CloudShirt

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: vockey

Resources:
  # --- Load Balancer ---

  loadBalancer1:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: loadBalancer1
      Type: application
      Scheme: internet-facing
      Subnets:
        - !ImportValue publicSubnet1
        - !ImportValue publicSubnet2
      SecurityGroups:
        - !ImportValue securityGroupLoadBalancer1

  # --- Target Group ---

  loadBalancer1TargetGroup1:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: loadBalancer1TargetGroup1
      Port: 5000
      Protocol: HTTP
      VpcId: !ImportValue vpc1
      TargetType: instance

  # --- Listener ---

  loadbalancer1Listener1:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref loadBalancer1
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref loadBalancer1TargetGroup1

  # --- Launch Template ---

  launchTemplate1:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: cloudShirtLaunchTemplate
      LaunchTemplateData:
        ImageId: ami-0e95a5e2743ec9ec9
        InstanceType: t3.small
        KeyName: !Ref KeyName
        SecurityGroupIds:
          - !ImportValue securityGroupInstance1
        UserData:
          Fn::Base64: !Sub
            - |
              #!/bin/bash
              set -eux

              # --- Update OS en dependencies ---
              yum update -y

              # --- Installeer Git en .NET 6 SDK ---
              rpm -Uvh https://packages.microsoft.com/config/centos/8/packages-microsoft-prod.rpm
              yum install -y dotnet-sdk-6.0 git

              # --- Clone CloudShirt naar de juiste map ---
              su - ec2-user -c "
                mkdir -p ~/CloudShirt
                cd ~/CloudShirt
                git clone https://github.com/looking4ward/CloudShirt.git .
              "

              # --- Pas appsettings.json aan met RDS endpoint ---
              sed -i 's/Server.*CatalogDb;/Server=${RDSENDPOINT},1433;User ID=csadmin;Password=cspasswd;Initial Catalog=Microsoft.eShopOnWeb.CatalogDb;/' /home/ec2-user/CloudShirt/src/Web/appsettings.json
              sed -i 's/Server.*Identity;/Server=${RDSENDPOINT},1433;User ID=csadmin;Password=cspasswd;Initial Catalog=Microsoft.eShopOnWeb.Identity;/' /home/ec2-user/CloudShirt/src/Web/appsettings.json

              # --- Build & publish .NET Web app ---
              su - ec2-user -c "
                export DOTNET_CLI_HOME=/home/ec2-user
                export ASPNETCORE_ENVIRONMENT=Development
                cd ~/CloudShirt/src/Web
                dotnet publish -c Release -o ~/CloudShirt/release
              "

              # --- Maak een systemd service ---
              cat << 'EOF' > /etc/systemd/system/cloudshirt.service
              [Unit]
              Description=CloudShirt Web Application
              After=network.target

              [Service]
              WorkingDirectory=/home/ec2-user/CloudShirt/release
              ExecStart=/usr/bin/dotnet /home/ec2-user/CloudShirt/release/Web.dll --urls "http://0.0.0.0:5000"
              Restart=always
              RestartSec=10
              KillSignal=SIGINT
              SyslogIdentifier=cloudshirt
              User=ec2-user
              Environment=DOTNET_CLI_HOME=/home/ec2-user

              [Install]
              WantedBy=multi-user.target
              EOF

              # --- Service activeren ---
              systemctl daemon-reload
              systemctl enable cloudshirt.service
              systemctl start cloudshirt.service
            - RDSENDPOINT: !ImportValue rds1EndpointAddress
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Stack
                Value: cloudshirt-elb

  # --- Auto Scaling Group ---

  autoScalingGroup1:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: autoScalingGroup1
      VPCZoneIdentifier:
        - !ImportValue publicSubnet1
        - !ImportValue publicSubnet2
      LaunchTemplate:
        LaunchTemplateId: !Ref launchTemplate1
        Version: !GetAtt launchTemplate1.LatestVersionNumber
      MinSize: 1
      MaxSize: 3
      DesiredCapacity: 1
      TargetGroupARNs:
        - !Ref loadBalancer1TargetGroup1
      HealthCheckType: EC2
      Tags:
        - Key: Name
          Value: cloudshirt-elb
          PropagateAtLaunch: true

  # --- Scheduled Scaling ---

  scaleOutSchedule1:
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName: !Ref autoScalingGroup1
      DesiredCapacity: 3
      MinSize: 1
      MaxSize: 3
      Recurrence: "0 18 * * *"  # Scale out at 6 PM ET
      TimeZone: "America/New_York"

  scaleInSchedule1:
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName: !Ref autoScalingGroup1
      DesiredCapacity: 1
      MinSize: 1
      MaxSize: 3
      Recurrence: "0 20 * * *"  # Scale in at 8 PM ET
      TimeZone: "America/New_York"
