Description: CloudShirt ELK Stack

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: vockey

Resources:
  securityGroupElk1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: cloudshirt-elk-sg 
      GroupDescription: Security group for CloudShirt ELK instance
      VpcId: !ImportValue vpc1
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5601
          ToPort: 5601
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9200
          ToPort: 9200
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5044
          ToPort: 5044
          CidrIp: 0.0.0.0/0 
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: securityGroupElk1 

  elkInstance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.medium  
      KeyName: !Ref KeyName 
      ImageId: ami-0bdd88bd06d16ba03 
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !ImportValue publicSubnet1
          GroupSet:
            - !Ref securityGroupElk1
      Tags:
        - Key: Name
          Value: elkInstance1 
      UserData: !Base64 |
        #!/bin/bash
        set -eux
        exec > /var/log/userdata.log 2>&1

        # --- Install dependencies ---
        yum install -y java-11 

        # --- Add Elastic repo ---
        rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

        cat <<EOF > /etc/yum.repos.d/elasticsearch.repo
        [elasticsearch]
        name=Elasticsearch repository
        baseurl=https://artifacts.elastic.co/packages/8.x/yum
        gpgcheck=1
        gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled=1
        autorefresh=1
        type=rpm-md
        EOF


        # Import GPG key
        sudo rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

        yum clean all
        yum makecache

        # --- Install Elasticsearch, Logstash, Kibana ---
        yum install -y elasticsearch logstash kibana

        # --- Configure Elasticsearch ---
        echo "network.host: 0.0.0.0" >> /etc/elasticsearch/elasticsearch.yml
        echo "http.port: 9200" >> /etc/elasticsearch/elasticsearch.yml
        echo "discovery.seed_hosts: []" >> /etc/elasticsearch/elasticsearch.yml
        # echo "xpack.security.enabled: false" >> /etc/elasticsearch/elasticsearch.yml

        systemctl enable elasticsearch
        systemctl start elasticsearch

        # --- Wait until Elasticsearch is ready ---
        # until curl -s http://127.0.0.1:9200 >/dev/null || curl -s http://$(hostname -I | awk '{print $1}'):9200 >/dev/null; do
        #   echo "Waiting for Elasticsearch..."
        #   sleep 5
        # done


        # --- Configure Kibana ---
        echo 'server.host: "0.0.0.0"' >> /etc/kibana/kibana.yml
        echo 'elasticsearch.hosts: ["http://localhost:9200"]' >> /etc/kibana/kibana.yml

        systemctl enable kibana
        systemctl start kibana

        # --- Configure Logstash for Filebeat input ---
        mkdir -p /etc/logstash/conf.d

        cat <<'EOF' > /etc/logstash/conf.d/02-beats-input.conf
        input {
          beats {
            port => 5044
          }
        }

        filter {
          # Optionally parse logs here, for now we just pass them through
        }

        output {
          elasticsearch {
            hosts => ["http://localhost:9200"]
            index => "cloudshirt-%{+YYYY.MM.dd}"
          }
        }
        EOF

        systemctl enable logstash
        systemctl start logstash

Outputs:
  ELKPublicIP:
    Description: Public IP to access ELK instance
    Value: !GetAtt elkInstance1.PublicIp
    Export:
      Name: ELKPublicIP

  KibanaURL:
    Description: Kibana URL
    Value: !Sub "http://${elkInstance1.PublicIp}:5601"
